#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Sun Apr  2 13:42:49 CST 2017
# Module: centos
# Submodule: 
# Command: hostname
###############################################################################

source "${HI_CLI_HOME}/bin/colors"
source "${HI_CLI_HOME}/bin/clap"
source "${HI_CLI_HOME}/bin/logging"
###############################################################################
function set_hostname() {
  OLD_HOSTNAME="$( hostname )"
  NEW_HOSTNAME="$1"

  if [ -z "$NEW_HOSTNAME" ]; then
    echo -n "Please input new hostname: "
    read NEW_HOSTNAME < /dev/tty
  fi

  if [ -z "$NEW_HOSTNAME" ]; then
    echo "Erro. Hostname incorrecto ou em falta. A sair..."
    exit 1
  fi

  echo "A alterar hostname de $OLD_HOSTNAME para $NEW_HOSTNAME..."

  hostnamectl set-hostname $NEW_HOSTNAME
  hostnamectl set-hostname $NEW_HOSTNAME --static
  hostnamectl set-hostname $NEW_HOSTNAME --transient

  sed -i "s/HOSTNAME=.*/HOSTNAME=$NEW_HOSTNAME/g" /etc/sysconfig/network

  if [ -n "$( grep "$OLD_HOSTNAME" /etc/hosts )" ]; then
    sed -i "s/$OLD_HOSTNAME/$NEW_HOSTNAME/g" /etc/hosts
  else
    echo -e "$( hostname -I | awk '{ print $1 }' )\t$NEW_HOSTNAME" >> /etc/hosts
  fi

  if [ -n "$( grep "$OLD_HOSTNAME" /etc/mailname )" ]; then
    sed -i "s/$OLD_HOSTNAME/$NEW_HOSTNAME/g" /etc/mailname
  else
    echo -e "$( hostname -I | awk '{ print $1 }' )\t$NEW_HOSTNAME" >> /etc/mailname
  fi
}


function run() {
  cli="hi centos set hostname"

  set_hostname "${arg3}"

  result=$?

  eval $1="\${result}"
  eval $2="\${cli}"
}

###############################################################################
